### ISSUE TITLE
 PACKAGE_HOME=$(pwd)  used incorrectly in activate.bash

### ISSUE THREAD

**Issue by bryanwb** [tlrobinson/narwhal#44]
in activate.bash,  PACKAGE_HOME=$(pwd)  which should be narwhal/bin, the same directory as the narwhal executable. Later activate.bash looks for narwhal in  PACKAGE_HOME/bin which is actually  narwhal/bin/bin 

I am having this problem on Ubuntu 9.04

**Comment by bryanwb** [comment]
never mind, the problem is something different

**Comment by tlrobinson** [comment]
pwd returns the current working directory rather than the bin directory.

The idea is that you'll probably be running this from a "sea", so it can guess it's location.

We should figure out why "${BASH_ARGV[0]}" is not correct for you. Are you using bash, or something else? This will only work with bash.

**Comment by bryanwb** [comment]
tom, this bug was reported in error. I was having problems due to the openjdk bug we discussed yesterday. I am closing the ticket
