### ISSUE TITLE
WebWorker implementation

### ISSUE THREAD

**Issue by kriszyp** [tlrobinson/narwhal#50]
Add WebWorker implementation that I created in http://github.com/kriszyp/narwhal/
A few implementations notes:
- Yesterday, I checked in a worker-engine.js module in /engines/rhino/lib for the Rhino-specific code, and refactored the rest of the code to /engines/default/lib/worker.js to hopefully make it easier to add support for workers on other platforms.
- This implementation relies heavily on a blocking queue object. I created an engines/rhino/lib/event-queue.js to provide the blocking queue implementation and act as the event queue for a worker. However, I am not sure if that was the intent of the existing reactor.js module (not sure I understand the term "reactor". I wasn't certain, so I didn't overwrite it in my fork, but I am guessing that those would need to become one.

**Comment by tlrobinson** [comment]
This looks great. I'm pulling it in.

However, I've been playing with it and I'm having trouble getting the onmessage for the parent to fire. Here's a trivial example:

worker-test.js:

```
var Worker = require("worker").Worker,
    FILE = require("file");

var echoWorker = new Worker(FILE.join(FILE.dirname(module.path), "echo-worker.js"));  

echoWorker.onmessage = function(event) {  
  print("Got: " + event.data);  
};

echoWorker.postMessage("hello");  
```

echo-worker.js:

```
onmessage = function(event) {
    print("Worker echoing: " + event.data);
    postMessage(event.data)
}
```

I get the "Worker echoing" message but not the "Got" message. Am I doing something wrong?

Also, I'm not sure if this is feasible, but it would be nice if we could pass relative module ids to Worker rather than having to construct an absolute path. Perhaps using Kris Kowal's xNarwhalCurryId thing? I'm not sure if it applies in this case. Kris?

**Comment by kriszyp** [comment]
The main thread/worker does not automatically enter the event loop (I made all the instantiated workers automatically enter the event loop in order to be compatible with the web workers paradigm, but the main one doesn't), as there was a lot of resistance to automatically executing the event loop on the mailing list (from me as well). In order to get your example to work, you need to manually enter the event-loop in worker-test.js at the end:

```
 var queue = require("event-queue");
 while(true){
      queue.nextEvent()();
 }
```

That would be great if we handled relative paths correctly. I am still new to how the narwhal module loader works, but maybe if you have some info/direction on how to do that maybe I could implement that.

**Comment by tlrobinson** [comment]
Got it, thanks. I pushed an example adapted from some MDC documentation:

http://github.com/tlrobinson/narwhal/blob/master/examples/fibonacci.js
http://github.com/tlrobinson/narwhal/blob/master/examples/fibonacci-worker.js

Starting new Narwhal workers takes a long time due to our poor load time of Narwhal. performance. I wonder if it's possible to freeze and "deep" clone a Rhino scope that has all of the core of Narwhal (but not the main module and it's dependencies) loaded?

**Comment by kriszyp** [comment]
Yeah, I am sure there is room for a lot of optimizations here. Having a deeply frozen global would indeed be safely shareable across workers, and would be a huge performance advantage (it would also be nice to be able to share other immutable data across workers, which is safe). However, I don't think we can just deep freeze the global  whenever we create a worker. But, perhaps we could do a check and reuse the global if it is already deeply frozen (I think ES5 has a Object.isFrozen() that could be used recursively). Between the concurrency and security benefits, maybe we could encourage users to do a deep freezes.

**Comment by tlrobinson** [comment]
Forgot to close this one.
