### ISSUE TITLE
Template engine needs some attention

### ISSUE THREAD

**Issue by Gozala** [tlrobinson/narwhal#54]
I discovered very nasty bug recently with xulrunner engine. It seems that after some changes made on the way engines are installed loaded, you can easily obtain circular system module require. It was quite hard to find the reason therefor I decided to update template engine to protect others from the same bug.   

I still can't set damn labels so here is the link to the commit

http://github.com/Gozala/narwhal/commit/83ac772bf5f4ef9dbc242d38d2027f00e15abaaf

**Comment by kriskowal** [comment]
Thanks.  I'll set the labels.

**Comment by Gozala** [comment]
BTW I think I have discovered [related issue](http://github.com/tlrobinson/narwhal/issues/#issue/55)

**Comment by kriskowal** [comment]
Gozala, can we close this?  Please review the changes to narwhal.js and the engine template.  Instead of putting the enginePrefix in system.prefixes, we now inject it as a separate item.  If the enginePrefix is sent from the bootstrap into narwhal.js, it gets injected _ahead_ of the narwhal lib path.

**Comment by Gozala** [comment]
It took me some time before I figured out in which repo I had to look and in which branch :)

kriskowal/master 

looks ok and it seems to works with narwhal-xulrunner engine as well

Thanks

**Comment by kriskowal** [comment]
Closing.  Thanks.
